### ISSUE TITLE
"texture_16777215.png Not found"

### ISSUE THREAD

**Issue by JayFoxRox** [Olganix/Sw_Racer#38]
Sometimes we seem to generate textures for indices which don't exist (from the GLC_Player log):

```
"/home/fox/Data/Projects/Sw_Racer/build/output/out_modelblock.bin_66.bin.dae"
"texture_16777215.png Not found"
```

We should look for the specific rules when a texture should be created (I have documented this already in a current swe1r-re PR as far as I know).

**Comment by Olganix** [comment]
16777215 = 0xFFFFFF = -1 => empty.png

**Comment by Olganix** [comment]
a texture with more than 4 x4 pixels, with color(0, 0, 0, 0)

**Comment by JayFoxRox** [comment]
Why is the size important? I assume the size is a restriction of Collada, and not the game?

**Comment by Olganix** [comment]
?? 0x00FFFFFF is the max of the data in the Section5. because 0xFF000000 is for the texture tag 0x0A000000

**Comment by Olganix** [comment]
oh you may talk about  "4 x4 pixels" ? its because of filtering. the minimum to keep well a texture with 1 color is 4x4

**Comment by JayFoxRox** [comment]
Just for the record: The resolution and color above is not a limitation or choice of the game (or any other particular software). This is just because Olganix had problems with smaller textures in the past and (0, 0, 0, 0) probably looks correct.
The game will likely simply turn off texturing (or even rendering?) or something - we still have to research the exact behaviour.

*(This was discussed on the OpenSWE1R gitter.im)*
