### ISSUE TITLE
There are collision objects which don't use the default material in Collada export

### ISSUE THREAD

**Issue by JayFoxRox** [Olganix/Sw_Racer#39]
I have seen this in the collision for Model 131. I believe these might be referenced "Malt" ?

Or is this intentional?

**Comment by Olganix** [comment]
there is some Section5 without Section52 (I just turn off the warning when I pass from emd to collada). so it's might have this strange things to have texture on collision.

**Comment by JayFoxRox** [comment]
The game allows for a different top speed depending on the surface, so our collision export is incomplete as it doesn't describe surfaces (which should probably happen in the material).

The ice lake and icy tunnels on Ando Prime might also be handled in the collision object. But they could also be properties of the area (See #46 )

**Comment by JayFoxRox** [comment]
I blieve this was closed in 457dff8404da5a841dfed5676c268db37bd37055
If there's still issues with the implementation a new issue should be created.
